
# Component
module.exports = lemon.Component {
  package: 'i8'
  name: 'CancelLastDigit'

  data: {
    size: 50
  }

  template: (data) ->
    img {
      width: data.size
      height: data.size
      src: "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2aWV3Qm94PSIwIDAgNDAgNDAiIHZlcnNpb249IjEuMSI+CjxnIGlkPSJzdXJmYWNlMSI+CjxwYXRoIHN0eWxlPSIgZmlsbDojOThDQ0ZEOyIgZD0iTSA3LjI0MjE4OCAyOC41IEwgMC42MzI4MTMgMjAgTCA3LjI0MjE4OCAxMS41IEwgMzkuNSAxMS41IEwgMzkuNSAyOC41IFogIi8+CjxwYXRoIHN0eWxlPSIgZmlsbDojNDc4OEM3OyIgZD0iTSAzOSAxMiBMIDM5IDI4IEwgNy40ODgyODEgMjggTCAxLjI2NTYyNSAyMCBMIDcuNDg4MjgxIDEyIEwgMzkgMTIgTSA0MCAxMSBMIDcgMTEgTCAwIDIwIEwgNyAyOSBMIDQwIDI5IFogIi8+CjxwYXRoIHN0eWxlPSIgZmlsbDojRkZGRkZGOyIgZD0iTSAyMiAxOCBDIDIwLjg2NzE4OCAxOCAyMCAxOC44NjcxODggMjAgMjAgQyAyMCAyMS4xMzI4MTMgMjAuODY3MTg4IDIyIDIyIDIyIEMgMjMuMTMyODEzIDIyIDI0IDIxLjEzMjgxMyAyNCAyMCBDIDI0IDE4Ljg2NzE4OCAyMy4xMzI4MTMgMTggMjIgMTggWiAiLz4KPC9nPgo8L3N2Zz4K"
    }
}