
# Component
module.exports = lemon.Component {
  package: 'i8'
  name: 'LessThan'

  data: {
    size: 50
  }

  template: (data) ->
    img {
      width: data.size
      height: data.size
      src: "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2aWV3Qm94PSIwIDAgNDAgNDAiIHZlcnNpb249IjEuMSI+CjxnIGlkPSJzdXJmYWNlMSI+CjxwYXRoIHN0eWxlPSIgZmlsbDojREZGMEZFOyIgZD0iTSA0LjUgMjIuNjMyODEzIEwgNC41IDE2LjM2NzE4OCBMIDM1LjUgMS43ODkwNjMgTCAzNS41IDcuMzE2NDA2IEwgOS41ODk4NDQgMTkuNSBMIDM1LjUgMzEuNjgzNTk0IEwgMzUuNSAzNy4yMTA5MzggWiAiLz4KPHBhdGggc3R5bGU9IiBmaWxsOiM0Nzg4Qzc7IiBkPSJNIDM1IDIuNTc0MjE5IEwgMzUgNi45OTYwOTQgTCAxMC4zMzk4NDQgMTguNTkzNzUgTCA4LjQxNDA2MyAxOS41IEwgMTAuMzM5ODQ0IDIwLjQwNjI1IEwgMzUgMzIgTCAzNSAzNi40MjU3ODEgTCA1IDIyLjMxMjUgTCA1IDE2LjY4NzUgTCAzNSAyLjU3NDIxOSBNIDM2IDEgTCA0IDE2LjA1MDc4MSBMIDQgMjIuOTQ5MjE5IEwgMzYgMzggTCAzNiAzMS4zNjcxODggTCAxMC43NjU2MjUgMTkuNSBMIDM2IDcuNjMyODEzIFogIi8+CjwvZz4KPC9zdmc+Cg=="
    }
}