
# Component
module.exports = lemon.Component {
  package: 'i8'
  name: 'Polygon'

  data: {
    size: 50
  }

  template: (data) ->
    img {
      width: data.size
      height: data.size
      src: "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2aWV3Qm94PSIwIDAgNDAgNDAiIHZlcnNpb249IjEuMSI+CjxnIGlkPSJzdXJmYWNlMSI+CjxwYXRoIHN0eWxlPSIgZmlsbDojREZGMEZFOyIgZD0iTSAxNS42MzI4MTMgMzcuNSBMIDIuNSAzMC4xMTcxODggTCAyLjUgMTUuNjA1NDY5IEwgOC4yMTA5MzggMi41IEwgMjIuNjYwMTU2IDIuNSBMIDM3LjUgMTEuMjg1MTU2IEwgMzcuNSAyNS43Njk1MzEgTCAzMC4xMzY3MTkgMzcuNSBaICIvPgo8cGF0aCBzdHlsZT0iIGZpbGw6IzQ3ODhDNzsiIGQ9Ik0gMjIuNTIzNDM4IDMgTCAzNyAxMS41NzAzMTMgTCAzNyAyNS42MjUgTCAyOS44NTkzNzUgMzcgTCAxNS43NjE3MTkgMzcgTCAzIDI5LjgyODEyNSBMIDMgMTUuNzA3MDMxIEwgOC41MzkwNjMgMyBMIDIyLjUyMzQzOCAzIE0gMjIuNzk2ODc1IDIgTCA3Ljg4NjcxOSAyIEwgMiAxNS41IEwgMiAzMC40MTAxNTYgTCAxNS41IDM4IEwgMzAuNDEwMTU2IDM4IEwgMzggMjUuOTEwMTU2IEwgMzggMTEgWiAiLz4KPC9nPgo8L3N2Zz4K"
    }
}