
# Component
module.exports = lemon.Component {
  package: 'i8'
  name: 'ResizeHorizontal'

  data: {
    size: 50
  }

  template: (data) ->
    img {
      width: data.size
      height: data.size
      src: "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2aWV3Qm94PSIwIDAgNDAgNDAiIHZlcnNpb249IjEuMSI+CjxnIGlkPSJzdXJmYWNlMSI+CjxwYXRoIHN0eWxlPSIgZmlsbDojREZGMEZFOyIgZD0iTSAzMy41IDIyLjUgTCA2LjUgMjIuNSBMIDYuNSAyNS43OTI5NjkgTCAwLjcwNzAzMSAyMCBMIDYuNSAxNC4yMDcwMzEgTCA2LjUgMTcuNSBMIDMzLjUgMTcuNSBMIDMzLjUgMTQuMjA3MDMxIEwgMzkuMjkyOTY5IDIwIEwgMzMuNSAyNS43OTI5NjkgWiAiLz4KPHBhdGggc3R5bGU9IiBmaWxsOiM0Nzg4Qzc7IiBkPSJNIDM0IDE1LjQxNDA2MyBMIDM4LjU4NTkzOCAyMCBMIDM0IDI0LjU4NTkzOCBMIDM0IDIyIEwgNiAyMiBMIDYgMjQuNTg1OTM4IEwgMS40MTQwNjMgMjAgTCA2IDE1LjQxNDA2MyBMIDYgMTggTCAzNCAxOCBMIDM0IDE1LjQxNDA2MyBNIDMzIDEzIEwgMzMgMTcgTCA3IDE3IEwgNyAxMyBMIDAgMjAgTCA3IDI3IEwgNyAyMyBMIDMzIDIzIEwgMzMgMjcgTCA0MCAyMCBaICIvPgo8L2c+Cjwvc3ZnPgo="
    }
}